# Site settings
title: Ox XChem
subtitle: enabling hit-to-lead in FBDD
email: anthony.bradley@chem.ox.ac.uk
description: Offering computational and chemistry resource and assistance for hit-to-lead in fragment-based drug design.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Anthony Bradley

building:
street_address: Chemistry Research Laboratory
city: 12 Mansfield Rd
state: Oxford
zip_code: OX1 3TA
country: United Kingdom
phone: 07572492192

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# Social settings
500px_url:
github_url: https://github.com/xchem
slack_url: https://xchem.slack.com/

# Build settings
markdown: kramdown

sass:
  style: compressed
